"""add_user_profile_change_logs_and_email_verification_requests

Revision ID: 0451efd39730
Revises: 00a0310610c1
Create Date: 2026-04-09 17:48:10.165950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0451efd39730'
down_revision: Union[str, None] = '00a0310610c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('requested_email', sa.String(), nullable=False),
    sa.Column('verification_type', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(), nullable=True),
    sa.Column('sent_via', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sent_via IN ('gmail_api')", name='ck_email_verification_requests_sent_via'),
    sa.CheckConstraint("verification_type IN ('signup', 'email_change')", name='ck_email_verification_requests_verification_type'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('email_verification_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_requests_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_requests_requested_email'), ['requested_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_requests_user_id'), ['user_id'], unique=False)

    op.create_table('user_profile_change_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('before_email', sa.String(), nullable=True),
    sa.Column('after_email', sa.String(), nullable=True),
    sa.Column('before_name', sa.String(), nullable=True),
    sa.Column('after_name', sa.String(), nullable=True),
    sa.Column('before_full_name', sa.String(), nullable=True),
    sa.Column('after_full_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actor_role IN ('admin', 'employee')", name='ck_user_profile_change_logs_actor_role'),
    sa.CheckConstraint("event_type IN ('profile', 'password', 'email_change_requested', 'email_change_confirmed')", name='ck_user_profile_change_logs_event_type'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile_change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_change_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_change_logs_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_change_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_change_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('user_profile_change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_change_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profile_change_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_user_profile_change_logs_changed_at'))
        batch_op.drop_index(batch_op.f('ix_user_profile_change_logs_actor_user_id'))

    op.drop_table('user_profile_change_logs')
    with op.batch_alter_table('email_verification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_requests_requested_email'))
        batch_op.drop_index(batch_op.f('ix_email_verification_requests_expires_at'))

    op.drop_table('email_verification_requests')
    # ### end Alembic commands ###
