"""initial_schema

Revision ID: 13ecfcc50f59
Revises: 
Create Date: 2026-04-04 18:54:32.953990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ecfcc50f59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('google_calendar_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'employee')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('attendances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_idm', sa.String(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('updated_reason', sa.String(), nullable=True),
    sa.Column('last_updated_by_user_id', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('desktop_nfc', 'desktop_user_id', 'admin_manual', 'self_service')", name='ck_attendances_source'),
    sa.CheckConstraint('check_out IS NULL OR check_out > check_in', name='ck_attendances_checkout_after_checkin'),
    sa.ForeignKeyConstraint(['last_updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_date', name='uq_attendances_user_work_date')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_work_date'), ['work_date'], unique=False)

    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_idm', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_card_idm'), ['card_idm'], unique=True)
        batch_op.create_index(batch_op.f('ix_cards_user_id'), ['user_id'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('google_event_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_event_id', name='uq_shifts_google_event_id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_shift_date'), ['shift_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_user_id'), ['user_id'], unique=False)

    op.create_table('attendance_change_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attendance_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('before_check_in', sa.DateTime(), nullable=True),
    sa.Column('before_check_out', sa.DateTime(), nullable=True),
    sa.Column('after_check_in', sa.DateTime(), nullable=True),
    sa.Column('after_check_out', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actor_role IN ('admin', 'employee')", name='ck_attendance_change_logs_actor_role'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_change_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_change_logs_attendance_id'), ['attendance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_change_logs_changed_at'), ['changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_change_logs_changed_at'))
        batch_op.drop_index(batch_op.f('ix_attendance_change_logs_attendance_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_change_logs_actor_user_id'))

    op.drop_table('attendance_change_logs')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_user_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_shift_date'))

    op.drop_table('shifts')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_cards_card_idm'))

    op.drop_table('cards')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_work_date'))
        batch_op.drop_index(batch_op.f('ix_attendances_user_id'))

    op.drop_table('attendances')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
