"""add_manual_work_time_columns

Revision ID: 152eb743ff23
Revises: 30ee79160527
Create Date: 2026-06-23 14:49:06.566644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152eb743ff23'
down_revision: Union[str, None] = '30ee79160527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_change_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_work_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('before_work_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('after_work_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('after_work_end', sa.DateTime(), nullable=True))

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('work_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_manual_work_time', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_system_settings_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_system_settings_key'), ['key'])

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('is_manual_work_time')
        batch_op.drop_column('work_end')
        batch_op.drop_column('work_start')

    with op.batch_alter_table('attendance_change_logs', schema=None) as batch_op:
        batch_op.drop_column('after_work_end')
        batch_op.drop_column('after_work_start')
        batch_op.drop_column('before_work_end')
        batch_op.drop_column('before_work_start')

    # ### end Alembic commands ###
