"""add auto complete to attendances

Revision ID: 57d3ee477444
Revises: ffa1834a4fc2
Create Date: 2026-06-09 10:29:08.942390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d3ee477444'
down_revision: Union[str, None] = 'ffa1834a4fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_auto_completed', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('auto_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('auto_completed_at')
        batch_op.drop_column('is_auto_completed')

    # ### end Alembic commands ###
