"""Add attendance_alert_acknowledgments

Revision ID: 5be86b014bc7
Revises: d78c3d445639
Create Date: 2026-07-08 09:10:20.812682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be86b014bc7'
down_revision: Union[str, None] = 'd78c3d445639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_alert_acknowledgments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_alert_acknowledgments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_alert_acknowledgments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_alert_acknowledgments_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_alert_acknowledgments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_alert_acknowledgments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_alert_acknowledgments_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_alert_acknowledgments_rule_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_alert_acknowledgments_date'))

    op.drop_table('attendance_alert_acknowledgments')
    # ### end Alembic commands ###
