"""drop_password_hash

Revision ID: 6d3c122ccdd4
Revises: 57d3ee477444
Create Date: 2026-06-09 13:52:02.689943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3c122ccdd4'
down_revision: Union[str, None] = '57d3ee477444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('user_profile_change_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_user_profile_change_logs_event_type', type_='check')
        batch_op.create_check_constraint(
            'ck_user_profile_change_logs_event_type',
            "event_type IN ('profile', 'email_change_requested', 'email_change_confirmed')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile_change_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_user_profile_change_logs_event_type', type_='check')
        batch_op.create_check_constraint(
            'ck_user_profile_change_logs_event_type',
            "event_type IN ('profile', 'password', 'email_change_requested', 'email_change_confirmed')"
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
