"""add device_name to attendance

Revision ID: d78c3d445639
Revises: b53e7a50ac48
Create Date: 2026-07-06 17:29:23.249871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78c3d445639'
down_revision: Union[str, None] = 'b53e7a50ac48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_attendances')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('device_name')

    op.create_table('_alembic_tmp_attendances',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('card_idm', sa.VARCHAR(), nullable=True),
    sa.Column('work_date', sa.DATE(), nullable=False),
    sa.Column('check_in', sa.DATETIME(), nullable=True),
    sa.Column('check_out', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('updated_reason', sa.VARCHAR(), nullable=True),
    sa.Column('last_updated_by_user_id', sa.VARCHAR(), nullable=True),
    sa.Column('last_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_auto_completed', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('auto_completed_at', sa.DATETIME(), nullable=True),
    sa.Column('work_start', sa.DATETIME(), nullable=True),
    sa.Column('work_end', sa.DATETIME(), nullable=True),
    sa.Column('is_manual_work_time', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.CheckConstraint("source IN ('webusb_nfc', 'web_user_id', 'admin_manual', 'self_service')", name=op.f('ck_attendances_source')),
    sa.CheckConstraint('check_out IS NULL OR check_out > check_in', name=op.f('ck_attendances_checkout_after_checkin')),
    sa.ForeignKeyConstraint(['last_updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
