"""create_attendance_monthly_comments

Revision ID: d7b9076af7b7
Revises: ae4778d06bdb
Create Date: 2026-08-21 08:09:55.113625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b9076af7b7'
down_revision: Union[str, None] = 'ae4778d06bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_monthly_comments',
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('year_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_monthly_comments')
    # ### end Alembic commands ###
