"""add_attendance_correction_requests_and_locks

Revision ID: ffa1834a4fc2
Revises: a1b2c3d4e5f6
Create Date: 2026-06-01 09:38:22.478150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa1834a4fc2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_locks',
    sa.Column('year_month', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locked_by_user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('year_month')
    )
    op.create_table('attendance_correction_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attendance_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('requested_check_in', sa.DateTime(), nullable=True),
    sa.Column('requested_check_out', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('approved_by_user_id', sa.String(), nullable=True),
    sa.Column('approval_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_attendance_correction_requests_status'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_correction_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_correction_requests_attendance_id'), ['attendance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_correction_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_correction_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_correction_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_correction_requests_attendance_id'))

    op.drop_table('attendance_correction_requests')
    op.drop_table('attendance_locks')
    # ### end Alembic commands ###
